apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tk-abc.fullname" . }}-secret
  labels:
    {{- include "tk-abc.labels" . | nindent 4 }}
type: Opaque
data:
  telegram_bot_token: {{ .Values.secrets.telegramBotToken | b64enc | quote }}
  openai_api_key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  db_password: {{ .Values.secrets.dbPassword | b64enc | quote }}
